# Staging environment overrides
version: '3.8'

services:
  backend:
    environment:
      - DEBUG=False
      - LOG_LEVEL=WARNING
      - ENVIRONMENT=staging
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  postgres:
    environment:
      POSTGRES_DB: forex_prediction_staging
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis:
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M