[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "forex-backend"
source = "backend"

[services.variables]
PYTHONPATH = "/app"
PORT = "8080"

[[services]]
name = "forex-frontend"
source = "frontend"

[services.variables]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "postgres"
source = "postgres:15"

[services.variables]
POSTGRES_DB = "forex_prediction"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = { "$generate": "password" }

# Railway-specific configurations
[environments.production]
[environments.production.variables]
NODE_ENV = "production"
DEBUG = "False"
LOG_LEVEL = "ERROR"

[environments.staging]
[environments.staging.variables]
NODE_ENV = "staging"
DEBUG = "False" 
LOG_LEVEL = "WARNING"

[environments.development]
[environments.development.variables]
NODE_ENV = "development"
DEBUG = "True"
LOG_LEVEL = "DEBUG"