services:
  - type: web
    name: forex-prediction-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /api/health
    env: production
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: EXCHANGE_RATES_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://forex-prediction-frontend.vercel.app,http://localhost:3000