services:
  - type: web
    name: forex-prediction-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.render
    dockerContext: ./backend
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    env: production
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: API_PORT
        value: 8000
      - key: API_HOST
        value: 0.0.0.0